require("nvim-treesitter.configs").setup({
	sync_install = false,
	ignore_install = {},
	-- parser_install_dir = vim.fn.stdpath("data") .. "/nvim-treesitter/",
	-- ensure_installed = {
	-- 	"bash",
	-- 	"c",
	-- 	"diff",
	-- 	"html",
	-- 	"lua",
	-- 	"luadoc",
	-- 	"markdown",
	-- 	"markdown_inline",
	-- 	"query",
	-- 	"vim",
	-- 	"vimdoc",
	-- 	"scala",
	-- },
	-- auto_install = true,
	highlight = {
		enable = true,
		additional_vim_regex_highlighting = { "ruby" },
	},
	indent = { enable = true, disable = { "ruby" } },
})
